In [151]:
import pandas as pd
import numpy as np

arr = np.array([10, 20, 30, 40])
pd.Series(data = arr)

0    10
1    20
2    30
3    40
dtype: int64

In [152]:
labels = ["A", "B", "C", "D"] 
pd.Series(data = arr, index = labels)

A    10
B    20
C    30
D    40
dtype: int64

In [153]:
pd.Series(arr)

0    10
1    20
2    30
3    40
dtype: int64

In [154]:
pd.Series(arr, labels)

A    10
B    20
C    30
D    40
dtype: int64

In [155]:
ser1 = pd.Series([10, 20, 30, 40], index = ["Apple", "Mango", "Grapes", "Cherry"])

ser2 = pd.Series([10, 30, 40, 50], index = ["Apple", "Grapes", "Cherry", "Kiwi"])

ser1 + ser2

Apple     20.0
Cherry    80.0
Grapes    60.0
Kiwi       NaN
Mango      NaN
dtype: float64

In [156]:
ser1["Cherry"]

np.int64(40)

In [157]:
from numpy.random import randn
df = pd.DataFrame(randn(5, 4), index = "A B C D E".split(), columns = "W X Y Z".split())
df

          W         X         Y         Z
A -1.058599  0.805271 -0.175252  0.250953
B -1.453606 -0.820262 -1.536496 -0.345454
C -1.435978  0.606899 -0.423394 -0.558100
D -0.686637  0.503546  0.517656 -0.398588
E -0.293273  0.061940 -0.216525  0.229471

In [158]:
df["Z"]

A    0.250953
B   -0.345454
C   -0.558100
D   -0.398588
E    0.229471
Name: Z, dtype: float64

In [159]:
df[["Z", "W"]]

          Z         W
A  0.250953 -1.058599
B -0.345454 -1.453606
C -0.558100 -1.435978
D -0.398588 -0.686637
E  0.229471 -0.293273

In [160]:
df["NEW"] = df["Y"] + df["Z"]
df

          W         X         Y         Z       NEW
A -1.058599  0.805271 -0.175252  0.250953  0.075701
B -1.453606 -0.820262 -1.536496 -0.345454 -1.881950
C -1.435978  0.606899 -0.423394 -0.558100 -0.981494
D -0.686637  0.503546  0.517656 -0.398588  0.119068
E -0.293273  0.061940 -0.216525  0.229471  0.012946

In [161]:
df.drop(columns = "NEW")

          W         X         Y         Z
A -1.058599  0.805271 -0.175252  0.250953
B -1.453606 -0.820262 -1.536496 -0.345454
C -1.435978  0.606899 -0.423394 -0.558100
D -0.686637  0.503546  0.517656 -0.398588
E -0.293273  0.061940 -0.216525  0.229471

In [162]:
df

          W         X         Y         Z       NEW
A -1.058599  0.805271 -0.175252  0.250953  0.075701
B -1.453606 -0.820262 -1.536496 -0.345454 -1.881950
C -1.435978  0.606899 -0.423394 -0.558100 -0.981494
D -0.686637  0.503546  0.517656 -0.398588  0.119068
E -0.293273  0.061940 -0.216525  0.229471  0.012946

In [163]:
df.drop(columns = "NEW", axis = 1, inplace = True)
df

          W         X         Y         Z
A -1.058599  0.805271 -0.175252  0.250953
B -1.453606 -0.820262 -1.536496 -0.345454
C -1.435978  0.606899 -0.423394 -0.558100
D -0.686637  0.503546  0.517656 -0.398588
E -0.293273  0.061940 -0.216525  0.229471

In [164]:
df.loc["A"]

W   -1.058599
X    0.805271
Y   -0.175252
Z    0.250953
Name: A, dtype: float64

In [165]:
df.iloc[2]

W   -1.435978
X    0.606899
Y   -0.423394
Z   -0.558100
Name: C, dtype: float64

In [166]:
df.loc["A", "Y"]

np.float64(-0.1752521513055502)

In [167]:
df.loc[["A", "B"], ["X", "Y"]]

          X         Y
A  0.805271 -0.175252
B -0.820262 -1.536496

In [168]:
df>0

       W      X      Y      Z
A  False   True  False   True
B  False  False  False  False
C  False   True  False  False
D  False   True   True  False
E  False   True  False   True

In [169]:
df[df>0]

    W         X         Y         Z
A NaN  0.805271       NaN  0.250953
B NaN       NaN       NaN       NaN
C NaN  0.606899       NaN       NaN
D NaN  0.503546  0.517656       NaN
E NaN  0.061940       NaN  0.229471

In [170]:
df[df["W"]>0]

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

In [171]:
df["W"]>0

A    False
B    False
C    False
D    False
E    False
Name: W, dtype: bool

In [172]:
df[df["W"]>0] ["Y"]

Series([], Name: Y, dtype: float64)

In [173]:
df[df["W"]>0][["X", "Y"]]

Empty DataFrame
Columns: [X, Y]
Index: []

In [174]:
df[(df['W']>0) & (df['Y']>1)]
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[44,55,66,44],'col3':['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1    44  abc
1     2    55  def
2     3    66  ghi
3     4    44  xyz

In [175]:
df['col2'].unique()

array([44, 55, 66])

In [176]:
df['col3'].nunique()

4

In [177]:
df["col3"].value_counts()

col3
abc    1
def    1
ghi    1
xyz    1
Name: count, dtype: int64

In [178]:
newdf= df[(df['col1']>2) & (df['col2']==44)]
newdf

   col1  col2 col3
3     4    44  xyz

In [179]:
def times2(x):
 return x*2

In [180]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [181]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [182]:
df['col1'].sum()

np.int64(10)

In [183]:
del df['col1']
df

   col2 col3
0    44  abc
1    55  def
2    66  ghi
3    44  xyz

In [184]:
df.columns

Index(['col2', 'col3'], dtype='object')

In [185]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [186]:
df.sort_values(by='col2')

   col2 col3
0    44  abc
3    44  xyz
1    55  def
2    66  ghi

In [187]:
df.sort_values(by='col2', inplace = True)
df

   col2 col3
0    44  abc
3    44  xyz
1    55  def
2    66  ghi

In [188]:
df.isnull()

    col2   col3
0  False  False
3  False  False
1  False  False
2  False  False

In [189]:
df = pd.read_csv("/home/oem/Downloads/Salaries.csv")
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [190]:
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [191]:
df.tail()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148649,148650,Roy I Tillery,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [192]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

In [193]:
df['BasePay'].mean()

np.float64(66325.4488404877)

In [194]:
df['OvertimePay'].max()

np.float64(245131.88)

In [195]:
df[df['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle' ]

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [196]:
df['TotalPayBenefits'] [df['EmployeeName']== 'JOSEPH DRISCOLL']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [197]:
df[df['TotalPay'].max()==df['TotalPay']]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN

In [198]:
df[df['TotalPay'].min()==df['TotalPay']]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [200]:
df.groupby('Year')['BasePay'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [201]:
df['JobTitle'].nunique()

2159

In [202]:
df['JobTitle'].value_counts().head()

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [203]:
(df[df['Year']==2013]['JobTitle'].value_counts()==1).sum()

np.int64(202)

In [204]:
df['JobTitle'].apply(lambda str:('chief' in str.lower())).sum()

np.int64(627)

In [208]:
def find_chief(job_title):
  if 'chief' in job_title.lower().split():
    return True
  else:
    return False
      
df = pd.read_csv('/home/oem/Downloads/Salaries.csv')
sum(df['JobTitle'].apply(lambda x: find_chief(x)))

477